import lifecycle from "./capabilityLifecycle.json" with { type: "json" };
import { allowedRepoPaths } from "./clientSafeRequests.js";
import { allowedWorkflowIds } from "./githubApi.js";
import { objectSchema } from "./schemas.js";

export const supportedIntents = [
  "get_engineering_access_state",
  "operator_status",
  "get_paper_account",
  "execute_paper_decision",
  "get_baseline_bench",
  "run_baseline_bench",
  "get_hostile_judge",
  "run_hostile_judge",
  "get_strategy_factory",
  "run_strategy_factory",
  "get_champion_selection",
  "run_champion_selection",
  "get_forward_operation",
  "run_forward_operation",
  "get_directional_shadow",
  "run_directional_shadow",
  "get_directional_institutional_research",
  "run_directional_institutional_research",
  "get_institutional_research_portfolio",
  "register_institutional_hypothesis",
  "advance_institutional_hypothesis",
  "get_institutional_research_evaluation",
  "run_institutional_hypothesis_evaluation",
  "run_institutional_independent_judge",
  "get_live_qualification",
  "run_live_qualification",
  "get_rolling_research",
  "run_rolling_research",
  "get_historical_bootstrap",
  "run_historical_bootstrap",
  "get_hardening_status",
  "advance_hardening_incident",
  "read_continuation",
  "inspect_repository",
  "read_repo_file",
  "list_repo_files",
  "apply_repo_patch_set",
  "create_repo_file",
  "delete_repo_file",
  "run_validation",
  "list_github_actions_runs",
  "trigger_github_workflow",
  "monitor_github_workflow",
  "deploy_cloudflare_worker",
  "apply_d1_migrations",
  "validate_production_sha",
];

export const capabilityDirectory = [
  capability({
    id: "engineering.access_state",
    intent: "get_engineering_access_state",
    title: "Get Engineering Access State",
    operation_class: "read",
    handler_id: "get_engineering_access_state",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["worker_env"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "no_secrets_returned"],
    tests: ["get_engineering_access_state reports server-side capabilities without secrets"],
  }),
  capability({
    id: "operating.operator_status",
    intent: "operator_status",
    title: "Operator Status",
    operation_class: "read",
    handler_id: "operator_status",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["operator_status succeeds", "no response contains secret-looking values"],
  }),
  capability({
    id: "paper.account_read",
    intent: "get_paper_account",
    title: "Get Paper Account",
    operation_class: "read",
    handler_id: "get_paper_account",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "paper_only", "no_live_capital"],
    tests: ["paper account summary exposes reconciled paper state without live controls"],
  }),
  capability({
    id: "paper.decision_execute",
    intent: "execute_paper_decision",
    title: "Execute Paper Decision",
    operation_class: "mutation",
    handler_id: "execute_paper_decision",
    input_schema: objectSchema({
      decision: objectSchema({
        cycle_id: { type: "string", maxLength: 120 },
        decision_id: { type: "string", maxLength: 120 },
        portfolio_id: { type: "string", maxLength: 120 },
        market: { type: "string", enum: ["BTC-USD"] },
        action: { type: "string", enum: ["buy", "sell", "hold"] },
        signal_closed_at: { type: "string", maxLength: 40 },
        decision_at: { type: "string", maxLength: 40 },
        requested_notional_usd: { type: "number", minimum: 0.00000001 },
        requested_quantity: { type: "number", minimum: 0.00000001 },
      }, ["cycle_id", "decision_id", "portfolio_id", "market", "action", "signal_closed_at", "decision_at"]),
    }, ["decision"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "strict_schema", "paper_only", "no_live_capital", "no_leverage", "no_shorting"],
    tests: ["paper decisions enforce next-eligible-candle timing", "paper decisions reconcile accounting", "paper cycle replay creates no duplicate effects"],
  }),
  capability({
    id: "baseline.bench_read",
    intent: "get_baseline_bench",
    title: "Get Baseline Bench",
    operation_class: "read",
    handler_id: "get_baseline_bench",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "historical_paper_research", "no_live_capital"],
    tests: ["baseline bench summary exposes immutable historical results without promotion controls"],
  }),
  capability({
    id: "baseline.bench_run",
    intent: "run_baseline_bench",
    title: "Run Baseline Bench",
    operation_class: "mutation",
    handler_id: "run_baseline_bench",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_definitions", "fixed_partitions", "no_tuning", "no_promotion", "no_live_capital"],
    tests: ["baseline bench freezes predeclared definitions and partitions", "repeated baseline run replays without duplicate artifacts"],
  }),
  capability({
    id: "hostile_judge.summary_read",
    intent: "get_hostile_judge",
    title: "Get Hostile Judge",
    operation_class: "read",
    handler_id: "get_hostile_judge",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "no_promotion", "no_live_capital"],
    tests: ["hostile judge summary exposes verdict reasons without promotion controls"],
  }),
  capability({
    id: "hostile_judge.batch_run",
    intent: "run_hostile_judge",
    title: "Run Hostile Judge",
    operation_class: "mutation",
    handler_id: "run_hostile_judge",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "baseline_artifacts"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_gates", "integrity_verification", "no_promotion", "no_live_capital"],
    tests: ["hostile judge rejects corrupted or inactive evidence", "repeated hostile judge batch replays without duplicate verdicts"],
  }),
  capability({
    id: "strategy_factory.summary_read",
    intent: "get_strategy_factory",
    title: "Get Strategy Factory",
    operation_class: "read",
    handler_id: "get_strategy_factory",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "fixed_catalog", "no_tuning", "no_promotion", "no_live_capital"],
    tests: ["strategy factory summary exposes fixed candidate verdicts without search or promotion controls"],
  }),
  capability({
    id: "strategy_factory.batch_run",
    intent: "run_strategy_factory",
    title: "Run Strategy Factory",
    operation_class: "mutation",
    handler_id: "run_strategy_factory",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "baseline_benchmarks", "hostile_judge"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_catalog", "frozen_partitions", "unchanged_judge", "no_tuning", "no_promotion", "no_live_capital"],
    tests: ["strategy factory generates exactly eight predeclared candidates", "repeated factory batch replays without duplicate evidence"],
  }),
  capability({
    id: "selection.summary_read",
    intent: "get_champion_selection",
    title: "Get Champion Selection",
    operation_class: "read",
    handler_id: "get_champion_selection",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "qualified_only", "no_execution", "no_scheduling", "no_live_capital"],
    tests: ["selection summary exposes champion or no-champion blockers without execution controls"],
  }),
  capability({
    id: "selection.batch_run",
    intent: "run_champion_selection",
    title: "Run Champion Selection",
    operation_class: "mutation",
    handler_id: "run_champion_selection",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "strategy_candidate_verdicts"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_policy", "qualified_only", "deterministic_ranking", "no_execution", "no_scheduling", "no_live_capital"],
    tests: ["selection records no champion when no candidate is qualified", "repeated selection replays without replacement"],
  }),
  capability({
    id: "forward_operation.summary_read",
    intent: "get_forward_operation",
    title: "Get Forward Operation",
    operation_class: "read",
    handler_id: "get_forward_operation",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "paper_only", "no_live_capital"],
    tests: ["forward operation summary exposes cycle and scheduler state without live controls"],
  }),
  capability({
    id: "forward_operation.cycle_run",
    intent: "run_forward_operation",
    title: "Run Forward Operation",
    operation_class: "mutation",
    handler_id: "run_forward_operation",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles", "paper_ledger", "selection_batches"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "healthy_data_required", "qualified_champion_required", "next_candle_execution", "paper_only", "no_live_capital"],
    tests: ["forward operation idles without a champion", "forward operation uses only pre-execution candles and replays hourly cycles"],
  }),
  capability({
    id: "directional_shadow.summary_read",
    intent: "get_directional_shadow",
    title: "Get Directional Shadow Competition",
    operation_class: "read",
    handler_id: "get_directional_shadow",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "paper_only", "one_x_cap", "no_live_capital"],
    tests: ["directional shadow summary exposes isolated long short paper accounts without live controls"],
  }),
  capability({
    id: "directional_shadow.cycle_run",
    intent: "run_directional_shadow",
    title: "Run Directional Shadow Competition",
    operation_class: "mutation",
    handler_id: "run_directional_shadow",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles", "directional_shadow_portfolios"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "completed_candles_only", "next_candle_execution", "one_x_cap", "paper_only", "no_live_capital"],
    tests: ["directional shadow cycle replays by completed candle", "directional shadow cycle idempotency prevents duplicate effects"],
  }),
  capability({
    id: "directional_research.summary_read",
    intent: "get_directional_institutional_research",
    title: "Get Directional Institutional Research",
    operation_class: "read",
    handler_id: "get_directional_institutional_research",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "qualified_only", "paper_only", "no_live_capital"],
    tests: ["directional institutional research summary exposes the latest immutable batch without execution controls"],
  }),
  capability({
    id: "directional_research.batch_run",
    intent: "run_directional_institutional_research",
    title: "Run Directional Institutional Research",
    operation_class: "mutation",
    handler_id: "run_directional_institutional_research",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles", "directional_shadow_portfolios"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "completed_candles_only", "immutable_windows", "qualified_only", "cash_valid", "paper_only", "no_live_capital"],
    tests: ["directional institutional research persists exactly five windows and sixty runs", "repeated directional institutional research operation_id replays immutable evidence"],
  }),
  capability({
    id: "institutional_research.portfolio_read",
    intent: "get_institutional_research_portfolio",
    title: "Get Institutional Research Portfolio",
    operation_class: "read",
    handler_id: "get_institutional_research_portfolio",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "immutable_preregistration", "independent_judge_required", "stage13_authority_unchanged", "paper_only", "no_live_capital"],
    tests: ["institutional research portfolio summary exposes bounded hypotheses and throughput without Stage 13 promotion controls"],
  }),
  capability({
    id: "institutional_research.hypothesis_register",
    intent: "register_institutional_hypothesis",
    title: "Register Institutional Hypothesis",
    operation_class: "mutation",
    handler_id: "register_institutional_hypothesis",
    input_schema: objectSchema({
      hypothesis: objectSchema({
        id: { type: "string", minLength: 3, maxLength: 100, pattern: "^[a-z0-9][a-z0-9-]{2,99}$" },
        title: { type: "string", minLength: 1, maxLength: 180 },
        family: { type: "string", enum: ["trend", "breakout", "momentum", "volatility", "mean_reversion", "regime_filter"] },
        origin: { type: "string", enum: ["operator", "bounded_factory"] },
        market: { type: "string", enum: ["BTC-USD"] },
        interval: { type: "string", enum: ["1h"] },
        economic_mechanism: { type: "string", minLength: 1, maxLength: 3000 },
        market_premise: { type: "string", minLength: 1, maxLength: 3000 },
        expected_failure_modes: { type: "array", minItems: 1, maxItems: 12, items: { type: "string", minLength: 1, maxLength: 240 } },
        research_function: { type: "string", enum: ["alpha_research", "data_research", "execution_research", "portfolio_research", "risk_research"] },
        lineage_parent_id: { type: "string", minLength: 3, maxLength: 100, pattern: "^[a-z0-9][a-z0-9-]{2,99}$" },
        materially_new_evidence: { type: "string", minLength: 1, maxLength: 3000 },
        preregistration: objectSchema({
          spec_version: { type: "integer", enum: [2] },
          dataset_id: { type: "string", enum: ["btc-usd-1h-completed-4320-v1"] },
          strategy: objectSchema({
            template: { type: "string", enum: ["ema_trend", "donchian_breakout", "donchian_regime_breakout", "price_momentum", "regime_momentum", "volatility_breakout", "volatility_regime_breakout", "rsi_mean_reversion", "bollinger_mean_reversion"] },
            feature_set_id: { type: "string", enum: ["close-ema-v1", "ohlc-donchian-v1", "ohlc-donchian-regime-v1", "close-momentum-v1", "close-regime-momentum-v1", "ohlc-true-range-v1", "ohlc-true-range-regime-v1", "close-rsi-v1", "close-bollinger-v1"] },
            parameters: objectSchema({
              fast: { type: "integer", minimum: 2, maximum: 100 },
              slow: { type: "integer", minimum: 5, maximum: 300 },
              lookback: { type: "integer", minimum: 2, maximum: 240 },
              regime_lookback: { type: "integer", minimum: 24, maximum: 240 },
              regime_period: { type: "integer", minimum: 24, maximum: 240 },
              threshold_percent: { type: "number", minimum: 0.05, maximum: 10 },
              period: { type: "integer", minimum: 2, maximum: 240 },
              multiplier: { type: "number", minimum: 0.25, maximum: 5 },
              lower: { type: "number", minimum: 5, maximum: 45 },
              upper: { type: "number", minimum: 55, maximum: 95 },
              exit_lower: { type: "number", minimum: 20, maximum: 55 },
              exit_upper: { type: "number", minimum: 45, maximum: 80 },
              deviations: { type: "number", minimum: 0.5, maximum: 5 },
            }, []),
          }, ["template", "feature_set_id", "parameters"]),
          walk_forward_policy_id: { type: "string", enum: ["institutional-walk-forward-v1"] },
          cost_model_id: { type: "string", enum: ["institutional-cost-model-v1"] },
          judge_policy_id: { type: "string", enum: ["institutional-independent-judge-v1"] },
          evidence_integrity_policy_id: { type: "string", enum: ["institutional-evidence-integrity-v1"] },
        }, ["spec_version", "dataset_id", "strategy", "walk_forward_policy_id", "cost_model_id", "judge_policy_id", "evidence_integrity_policy_id"]),
        factory_admission: objectSchema({
          novelty_basis: { type: "string", minLength: 1, maxLength: 2000 },
          expected_information_gain: { type: "number", minimum: 0, maximum: 1 },
        }),
      }, ["id", "title", "family", "origin", "market", "interval", "economic_mechanism", "market_premise", "expected_failure_modes", "research_function", "preregistration"]),
    }, ["hypothesis"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "strict_schema", "immutable_preregistration", "bounded_factory", "rejected_lineage_requires_new_evidence", "no_stage13_promotion", "paper_only", "no_live_capital"],
    tests: ["institutional hypothesis registration is immutable by id and preregistration hash", "repeated operation_id replays institutional hypothesis registration without duplicate effects"],
  }),
  capability({
    id: "institutional_research.lifecycle_advance",
    intent: "advance_institutional_hypothesis",
    title: "Advance Institutional Hypothesis",
    operation_class: "mutation",
    handler_id: "advance_institutional_hypothesis",
    input_schema: objectSchema({
      hypothesis_id: { type: "string", minLength: 3, maxLength: 100, pattern: "^[a-z0-9][a-z0-9-]{2,99}$" },
      target_state: { type: "string", enum: ["proposed", "admitted", "testing", "rejected", "qualified", "retired", "superseded"] },
      reason_codes: { type: "array", maxItems: 12, items: { type: "string", minLength: 1, maxLength: 240 } },
      evidence_summary: { type: "string", minLength: 1, maxLength: 2000 },
      independent_verdict_id: { type: "string", minLength: 1, maxLength: 160 },
    }, ["hypothesis_id", "target_state"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "append_only_lifecycle", "rejection_terminal", "qualified_fail_closed", "independent_judge_required", "no_stage13_promotion", "paper_only", "no_live_capital"],
    tests: ["institutional lifecycle rejection is terminal and writes durable rejection memory", "repeated operation_id replays lifecycle transitions without duplicate effects"],
  }),
  capability({
    id: "institutional_research.evaluation_read",
    intent: "get_institutional_research_evaluation",
    title: "Get Institutional Research Evaluation",
    operation_class: "read",
    handler_id: "get_institutional_research_evaluation",
    input_schema: objectSchema({
      hypothesis_id: { type: "string", minLength: 3, maxLength: 100, pattern: "^[a-z0-9][a-z0-9-]{2,99}$" },
    }),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "sealed_evidence", "stage13_authority_unchanged", "paper_only", "no_live_capital"],
    tests: ["institutional evaluation summary exposes sealed artifacts and verdicts without promotion authority"],
  }),
  capability({
    id: "institutional_research.evaluation_run",
    intent: "run_institutional_hypothesis_evaluation",
    title: "Run Institutional Hypothesis Evaluation",
    operation_class: "mutation",
    handler_id: "run_institutional_hypothesis_evaluation",
    input_schema: objectSchema({
      hypothesis_id: { type: "string", minLength: 3, maxLength: 100, pattern: "^[a-z0-9][a-z0-9-]{2,99}$" },
    }, ["hypothesis_id"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "typed_preregistration", "sealed_historical_artifact", "completed_candles_only", "no_caller_metrics", "no_look_ahead", "stage13_authority_unchanged", "paper_only", "no_live_capital"],
    tests: ["institutional evaluator derives metrics only from sealed market data and typed spec", "repeated evaluation replays one immutable artifact per hypothesis"],
  }),
  capability({
    id: "institutional_research.independent_judge_run",
    intent: "run_institutional_independent_judge",
    title: "Run Institutional Independent Judge",
    operation_class: "mutation",
    handler_id: "run_institutional_independent_judge",
    input_schema: objectSchema({
      hypothesis_id: { type: "string", minLength: 3, maxLength: 100, pattern: "^[a-z0-9][a-z0-9-]{2,99}$" },
    }, ["hypothesis_id"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "independent_judge", "sealed_evaluator_artifact_required", "append_only_forward_evidence", "no_caller_metrics", "stage13_authority_unchanged", "paper_only", "no_live_capital"],
    tests: ["independent judge rejects weak sealed history", "historically qualified evidence awaits forward proof", "qualified verdict requires sealed historical and forward evidence", "repeated judge operation replays the same sealed evidence hash without duplicate verdict effects"],
  }),
  capability({
    id: "live_qualification.summary_read",
    intent: "get_live_qualification",
    title: "Get Live Qualification",
    operation_class: "read",
    handler_id: "get_live_qualification",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "evidence_only", "owner_approval_separate", "no_live_authorization", "no_funding", "no_credentials", "no_live_execution"],
    tests: ["qualification summary exposes all blockers and never authorizes live capital"],
  }),
  capability({
    id: "live_qualification.assessment_run",
    intent: "run_live_qualification",
    title: "Run Live Qualification",
    operation_class: "mutation",
    handler_id: "run_live_qualification",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "selection_batches", "forward_operation_cycles", "paper_ledger"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_policy", "evidence_only", "owner_approval_separate", "no_live_authorization", "no_funding", "no_credentials", "no_live_execution"],
    tests: ["qualification assessment remains not qualified without complete evidence", "repeated assessment replays the immutable result", "eligible evidence still requires separate owner approval"],
  }),
  capability({
    id: "rolling_research.summary_read",
    intent: "get_rolling_research",
    title: "Get Rolling Research",
    operation_class: "read",
    handler_id: "get_rolling_research",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "fixed_catalog", "paper_only", "no_live_capital"],
    tests: ["rolling research summary exposes waiting or complete epoch state without unsafe controls"],
  }),
  capability({
    id: "rolling_research.epoch_run",
    intent: "run_rolling_research",
    title: "Run Rolling Research",
    operation_class: "mutation",
    handler_id: "run_rolling_research",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles", "baseline_benchmarks", "strategy_factory_batches", "selection_batches"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "fixed_catalog", "fixed_partitions", "unchanged_judge", "qualified_only", "paper_only", "no_live_capital"],
    tests: ["rolling epoch waits without 720 candles", "repeated daily epoch replays immutable evidence"],
  }),
  capability({
    id: "historical_bootstrap.summary_read",
    intent: "get_historical_bootstrap",
    title: "Get Historical Bootstrap",
    operation_class: "read",
    handler_id: "get_historical_bootstrap",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "completed_candles_only", "no_synthetic_data", "no_paid_data", "paper_only", "no_live_capital"],
    tests: ["bootstrap summary exposes exact contiguous progress and blockers"],
  }),
  capability({
    id: "historical_bootstrap.attempt_run",
    intent: "run_historical_bootstrap",
    title: "Run Historical Bootstrap",
    operation_class: "mutation",
    handler_id: "run_historical_bootstrap",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["coinbase_exchange", "binance_us", "d1", "market_candles"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "bounded_windows", "immutable_candles", "conflict_rejection", "completed_candles_only", "no_synthetic_data", "no_paid_data", "paper_only", "no_live_capital"],
    tests: ["bootstrap resumes without duplicate effects", "repeated completed bootstrap replays immutable evidence"],
  }),
  capability({
    id: "engineering.hardening_status",
    intent: "get_hardening_status",
    title: "Get Hardening Status",
    operation_class: "read",
    handler_id: "get_hardening_status",
    input_schema: objectSchema({
      incident_id: { type: "string", maxLength: 160 },
      limit: { type: "number", minimum: 1, maximum: 50 },
    }),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "durable_incident_state"],
    tests: ["get_hardening_status returns bounded incidents and event evidence"],
  }),
  capability({
    id: "engineering.hardening_advance",
    intent: "advance_hardening_incident",
    title: "Advance Hardening Incident",
    operation_class: "mutation",
    handler_id: "advance_hardening_incident",
    input_schema: objectSchema({
      incident_id: { type: "string", maxLength: 160 },
      target_state: { type: "string", enum: ["diagnosed", "fixed", "validated", "deployed", "verified", "closed"] },
      root_cause: { type: "string", maxLength: 2000 },
      generalized_cause: { type: "string", maxLength: 2000 },
      prevention_rule_id: { type: "string", maxLength: 240 },
      regression_test_ids: { type: "array", maxItems: 20, items: { type: "string", maxLength: 240 } },
      tested_sha: { type: "string", maxLength: 40 },
      deployment_id: { type: "string", maxLength: 240 },
      live_verification_summary: { type: "string", maxLength: 2000 },
      resume_result_summary: { type: "string", maxLength: 2000 },
    }, ["incident_id", "target_state"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "ordered_state_machine", "prevention_before_closure"],
    tests: ["hardening transitions cannot skip states or close without complete evidence", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "operating.continuation_read",
    intent: "read_continuation",
    title: "Read Continuation",
    operation_class: "read",
    handler_id: "read_continuation",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_repository"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "canonical_git_authority"],
    tests: ["read_continuation returns the sole canonical Git ledger identity and current action"],
  }),
  capability({
    id: "engineering.repository_inspection",
    intent: "inspect_repository",
    title: "Inspect Repository",
    operation_class: "read",
    handler_id: "inspect_repository",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_metadata_config"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["inspect_repository returns compact repo state"],
  }),
  capability({
    id: "engineering.repo_file_read",
    intent: "read_repo_file",
    title: "Read Repository File",
    operation_class: "read",
    handler_id: "read_repo_file",
    input_schema: objectSchema({
      path: { type: "string", enum: allowedRepoPaths },
      ref: { type: "string", maxLength: 80 },
      start_line: { type: "number", minimum: 1 },
      max_lines: { type: "number", minimum: 1, maximum: 120 },
    }, ["path"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_paths: allowedRepoPaths,
    external_systems: ["bundled_repo_snapshot"],
    risk_gates: ["auth_required", "session_required", "path_allowlist", "bounded_output"],
    tests: ["read_repo_file only reads allowed paths", "forbidden path traversal rejects"],
  }),
  capability({
    id: "engineering.repo_files_list",
    intent: "list_repo_files",
    title: "List Repository Files",
    operation_class: "read",
    handler_id: "list_repo_files",
    input_schema: objectSchema({
      path: { type: "string", maxLength: 220 },
      ref: { type: "string", maxLength: 80 },
    }, []),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_paths: allowedRepoPaths,
    external_systems: ["github_contents_api"],
    risk_gates: ["auth_required", "session_required", "path_allowlist", "bounded_output"],
    tests: ["list_repo_files returns only allowlisted paths"],
  }),
  capability({
    id: "engineering.repo_patch_set",
    intent: "apply_repo_patch_set",
    title: "Apply Repository Patch Set",
    operation_class: "mutation",
    handler_id: "apply_repo_patch_set",
    input_schema: objectSchema({
      dry_run: { type: "boolean" },
      commit_message: { type: "string", maxLength: 160 },
      expected_head_sha: { type: "string", maxLength: 40 },
      replacements: {
        type: "array",
        minItems: 1,
        maxItems: 20,
        items: objectSchema({
          path: { type: "string", maxLength: 220 },
          find: { type: "string", maxLength: 12000 },
          replace: { type: "string", maxLength: 12000 },
        }, ["path", "find", "replace"]),
      },
    }, ["replacements"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_paths: allowedRepoPaths,
    external_systems: ["github_git_data_api"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "path_allowlist", "exact_find_replace", "single_commit", "no_arbitrary_shell"],
    tests: ["apply_repo_patch_set dry-runs exact replacements", "apply_repo_patch_set rejects non-unique matches", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.repo_file_create",
    intent: "create_repo_file",
    title: "Create Repository File",
    operation_class: "mutation",
    handler_id: "create_repo_file",
    input_schema: objectSchema({
      path: { type: "string", maxLength: 220 },
      content: { type: "string", maxLength: 50000 },
      commit_message: { type: "string", maxLength: 160 },
      expected_head_sha: { type: "string", maxLength: 40 },
    }, ["path", "content"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_git_data_api"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "path_allowlist", "single_commit"],
    tests: ["create_repo_file creates only allowed paths", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.repo_file_delete",
    intent: "delete_repo_file",
    title: "Delete Repository File",
    operation_class: "mutation",
    handler_id: "delete_repo_file",
    input_schema: objectSchema({
      path: { type: "string", maxLength: 220 },
      commit_message: { type: "string", maxLength: 160 },
      expected_head_sha: { type: "string", maxLength: 40 },
    }, ["path"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_git_data_api"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "path_allowlist", "single_commit"],
    tests: ["delete_repo_file deletes only allowed paths", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.validation",
    intent: "run_validation",
    title: "Run Validation",
    operation_class: "mutation",
    handler_id: "run_validation",
    input_schema: objectSchema({
      validation: {
        type: "string",
        enum: ["npm test", "npm run check", "production market data commission", "production paper ledger commission", "production baseline bench commission", "production hostile judge commission", "production strategy factory commission", "production champion selection commission", "production forward paper commission", "production live qualification commission", "production directional institutional research commission", "production rolling research commission", "production historical bootstrap commission"],
      },
    }, ["validation"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: ["npm test", "npm run check"],
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "no_arbitrary_shell"],
    tests: ["run_validation returns explicit not_available_in_worker_runtime", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.github_actions_runs_list",
    intent: "list_github_actions_runs",
    title: "List GitHub Actions Runs",
    operation_class: "read",
    handler_id: "list_github_actions_runs",
    input_schema: objectSchema({
      workflow_id: { type: "string", enum: allowedWorkflowIds },
      limit: { type: "number", minimum: 1, maximum: 20 },
    }, []),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: allowedWorkflowIds,
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "github_token_server_side", "bounded_output"],
    tests: ["list_github_actions_runs returns compact run metadata", "missing GitHub token is reported without exposing secrets"],
  }),
  capability({
    id: "engineering.github_workflow_dispatch",
    intent: "trigger_github_workflow",
    title: "Trigger GitHub Workflow",
    operation_class: "mutation",
    handler_id: "trigger_github_workflow",
    input_schema: objectSchema({
      workflow_id: { type: "string", enum: allowedWorkflowIds },
      ref: { type: "string", maxLength: 80 },
      deploy_sha: { type: "string", maxLength: 40 },
    }, ["workflow_id"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: allowedWorkflowIds,
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "workflow_allowlist", "no_arbitrary_shell"],
    tests: ["trigger_github_workflow dispatches only allowlisted workflows", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.github_workflow_monitor",
    intent: "monitor_github_workflow",
    title: "Monitor GitHub Workflow",
    operation_class: "read",
    handler_id: "monitor_github_workflow",
    input_schema: objectSchema({
      run_id: { type: "string", maxLength: 30 },
    }, ["run_id"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["monitor_github_workflow returns compact run and job state"],
  }),
  capability({
    id: "deployment.cloudflare_worker_dispatch",
    intent: "deploy_cloudflare_worker",
    title: "Deploy Cloudflare Worker",
    operation_class: "mutation",
    handler_id: "deploy_cloudflare_worker",
    input_schema: objectSchema({
      deploy_sha: { type: "string", maxLength: 40 },
    }, ["deploy_sha"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: ["quant-lab-deploy.yml"],
    external_systems: ["github_actions", "cloudflare"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "exact_sha_required", "cloudflare_secret_stays_in_github_actions"],
    tests: ["deploy_cloudflare_worker dispatches the fixed deploy workflow with an exact SHA", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "deployment.d1_migrations_dispatch",
    intent: "apply_d1_migrations",
    title: "Apply D1 Migrations",
    operation_class: "mutation",
    handler_id: "apply_d1_migrations",
    input_schema: objectSchema({
      deploy_sha: { type: "string", maxLength: 40 },
    }, ["deploy_sha"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: ["quant-lab-deploy.yml"],
    external_systems: ["github_actions", "cloudflare_d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "exact_sha_required", "cloudflare_secret_stays_in_github_actions", "no_arbitrary_sql"],
    tests: ["apply_d1_migrations dispatches fixed workflow in migrations mode", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "deployment.production_alignment",
    intent: "validate_production_sha",
    title: "Validate Production SHA",
    operation_class: "read",
    handler_id: "validate_production_sha",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["worker_env", "github_metadata_config"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["validate_production_sha returns compact alignment fields"],
  }),
];

export const lifecycleDeclarations = lifecycle.declarations;
export const lifecycleMandatorySequence = lifecycle.required_sequence;

export function resolveCapability(intent) {
  return capabilityDirectory.find((entry) => entry.intent === intent) || null;
}

export function resolveCapabilitySelector(selector) {
  return capabilityDirectory.find((entry) => entry.intent === selector || entry.id === selector) || null;
}

export function validateCapabilityLifecycle(directory = capabilityDirectory, declarations = lifecycleDeclarations) {
  const errors = [];
  if (lifecycle.version !== "quant-lab-capability-lifecycle-v2" || lifecycle.mandatory !== true) {
    errors.push("capability_lifecycle_version_or_mandatory_invalid");
  }
  const requiredFields = new Set(lifecycle.required_declaration_fields || []);
  const releaseScopes = new Set(lifecycle.allowed_release_scopes || []);
  const declarationByIntent = new Map();
  for (const declaration of declarations) {
    if (declarationByIntent.has(declaration.intent)) errors.push(`duplicate_lifecycle_intent:${declaration.intent}`);
    declarationByIntent.set(declaration.intent, declaration);
    for (const field of requiredFields) {
      if (!(field in declaration) || declaration[field] === null || declaration[field] === "") {
        errors.push(`missing_lifecycle_field:${declaration.intent}:${field}`);
      }
    }
    if (!releaseScopes.has(declaration.release_scope)) errors.push(`invalid_release_scope:${declaration.intent}`);
    if (declaration.compatibility_bridge !== false) errors.push(`compatibility_bridge_forbidden:${declaration.intent}`);
    if (typeof declaration.live_verification !== "string" || declaration.live_verification.length < 20) {
      errors.push(`live_verification_missing:${declaration.intent}`);
    }
  }
  for (const entry of directory) {
    const declaration = declarationByIntent.get(entry.intent);
    if (!declaration) {
      errors.push(`lifecycle_declaration_missing:${entry.intent}`);
      continue;
    }
    if (declaration.id !== entry.lifecycle_declaration_id) errors.push(`lifecycle_id_mismatch:${entry.intent}`);
    if (declaration.canonical_handler !== entry.handler_id) errors.push(`canonical_handler_mismatch:${entry.intent}`);
    if (!Array.isArray(entry.tests) || entry.tests.length < 1) errors.push(`focused_regression_missing:${entry.intent}`);
    if (entry.input_schema?.additionalProperties !== false) errors.push(`strict_schema_missing:${entry.intent}`);
  }
  for (const declaration of declarations) {
    if (!directory.some((entry) => entry.intent === declaration.intent)) errors.push(`orphan_lifecycle_declaration:${declaration.intent}`);
  }
  return { ok: errors.length === 0, errors };
}

export function assertCapabilityLifecycle() {
  const validation = validateCapabilityLifecycle();
  if (!validation.ok) throw new Error(`capability_lifecycle_invalid:${validation.errors.join("|")}`);
  return validation;
}

assertCapabilityLifecycle();

function capability(entry) {
  return {
    max_response_bytes: 12000,
    lifecycle_declaration_id: `${entry.id}.lifecycle`,
    ...entry,
  };
}
