import lifecycle from "./capabilityLifecycle.json" with { type: "json" };
import { allowedRepoPaths } from "./clientSafeRequests.js";
import { allowedWorkflowIds } from "./githubApi.js";
import { objectSchema } from "./schemas.js";

export const supportedIntents = [
  "get_engineering_access_state",
  "operator_status",
  "get_paper_account",
  "execute_paper_decision",
  "get_baseline_bench",
  "run_baseline_bench",
  "get_hostile_judge",
  "run_hostile_judge",
  "get_strategy_factory",
  "run_strategy_factory",
  "get_champion_selection",
  "run_champion_selection",
  "read_continuation",
  "write_continuation",
  "inspect_repository",
  "read_repo_file",
  "list_repo_files",
  "apply_repo_patch_set",
  "create_repo_file",
  "delete_repo_file",
  "run_validation",
  "list_github_actions_runs",
  "trigger_github_workflow",
  "monitor_github_workflow",
  "deploy_cloudflare_worker",
  "apply_d1_migrations",
  "validate_production_sha",
];

export const capabilityDirectory = [
  capability({
    id: "engineering.access_state",
    intent: "get_engineering_access_state",
    title: "Get Engineering Access State",
    operation_class: "read",
    handler_id: "get_engineering_access_state",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["worker_env"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "no_secrets_returned"],
    tests: ["get_engineering_access_state reports server-side capabilities without secrets"],
  }),
  capability({
    id: "operating.operator_status",
    intent: "operator_status",
    title: "Operator Status",
    operation_class: "read",
    handler_id: "operator_status",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["operator_status succeeds", "no response contains secret-looking values"],
  }),
  capability({
    id: "paper.account_read",
    intent: "get_paper_account",
    title: "Get Paper Account",
    operation_class: "read",
    handler_id: "get_paper_account",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "paper_only", "no_live_capital"],
    tests: ["paper account summary exposes reconciled paper state without live controls"],
  }),
  capability({
    id: "paper.decision_execute",
    intent: "execute_paper_decision",
    title: "Execute Paper Decision",
    operation_class: "mutation",
    handler_id: "execute_paper_decision",
    input_schema: objectSchema({
      decision: objectSchema({
        cycle_id: { type: "string", maxLength: 120 },
        decision_id: { type: "string", maxLength: 120 },
        portfolio_id: { type: "string", maxLength: 120 },
        market: { type: "string", enum: ["BTC-USD"] },
        action: { type: "string", enum: ["buy", "sell", "hold"] },
        signal_closed_at: { type: "string", maxLength: 40 },
        decision_at: { type: "string", maxLength: 40 },
        requested_notional_usd: { type: "number", minimum: 0.00000001 },
        requested_quantity: { type: "number", minimum: 0.00000001 },
      }, ["cycle_id", "decision_id", "portfolio_id", "market", "action", "signal_closed_at", "decision_at"]),
    }, ["decision"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "strict_schema", "paper_only", "no_live_capital", "no_leverage", "no_shorting"],
    tests: ["paper decisions enforce next-eligible-candle timing", "paper decisions reconcile accounting", "paper cycle replay creates no duplicate effects"],
  }),
  capability({
    id: "baseline.bench_read",
    intent: "get_baseline_bench",
    title: "Get Baseline Bench",
    operation_class: "read",
    handler_id: "get_baseline_bench",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "historical_paper_research", "no_live_capital"],
    tests: ["baseline bench summary exposes immutable historical results without promotion controls"],
  }),
  capability({
    id: "baseline.bench_run",
    intent: "run_baseline_bench",
    title: "Run Baseline Bench",
    operation_class: "mutation",
    handler_id: "run_baseline_bench",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "market_candles"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_definitions", "fixed_partitions", "no_tuning", "no_promotion", "no_live_capital"],
    tests: ["baseline bench freezes predeclared definitions and partitions", "repeated baseline run replays without duplicate artifacts"],
  }),
  capability({
    id: "hostile_judge.summary_read",
    intent: "get_hostile_judge",
    title: "Get Hostile Judge",
    operation_class: "read",
    handler_id: "get_hostile_judge",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "no_promotion", "no_live_capital"],
    tests: ["hostile judge summary exposes verdict reasons without promotion controls"],
  }),
  capability({
    id: "hostile_judge.batch_run",
    intent: "run_hostile_judge",
    title: "Run Hostile Judge",
    operation_class: "mutation",
    handler_id: "run_hostile_judge",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "baseline_artifacts"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_gates", "integrity_verification", "no_promotion", "no_live_capital"],
    tests: ["hostile judge rejects corrupted or inactive evidence", "repeated hostile judge batch replays without duplicate verdicts"],
  }),
  capability({
    id: "strategy_factory.summary_read",
    intent: "get_strategy_factory",
    title: "Get Strategy Factory",
    operation_class: "read",
    handler_id: "get_strategy_factory",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "fixed_catalog", "no_tuning", "no_promotion", "no_live_capital"],
    tests: ["strategy factory summary exposes fixed candidate verdicts without search or promotion controls"],
  }),
  capability({
    id: "strategy_factory.batch_run",
    intent: "run_strategy_factory",
    title: "Run Strategy Factory",
    operation_class: "mutation",
    handler_id: "run_strategy_factory",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "baseline_benchmarks", "hostile_judge"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_catalog", "frozen_partitions", "unchanged_judge", "no_tuning", "no_promotion", "no_live_capital"],
    tests: ["strategy factory generates exactly eight predeclared candidates", "repeated factory batch replays without duplicate evidence"],
  }),
  capability({
    id: "selection.summary_read",
    intent: "get_champion_selection",
    title: "Get Champion Selection",
    operation_class: "read",
    handler_id: "get_champion_selection",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "bounded_output", "qualified_only", "no_execution", "no_scheduling", "no_live_capital"],
    tests: ["selection summary exposes champion or no-champion blockers without execution controls"],
  }),
  capability({
    id: "selection.batch_run",
    intent: "run_champion_selection",
    title: "Run Champion Selection",
    operation_class: "mutation",
    handler_id: "run_champion_selection",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1", "strategy_candidate_verdicts"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "immutable_policy", "qualified_only", "deterministic_ranking", "no_execution", "no_scheduling", "no_live_capital"],
    tests: ["selection records no champion when no candidate is qualified", "repeated selection replays without replacement"],
  }),
  capability({
    id: "operating.continuation_read",
    intent: "read_continuation",
    title: "Read Continuation",
    operation_class: "read",
    handler_id: "read_continuation",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required"],
    tests: ["read_continuation returns idle when empty"],
  }),
  capability({
    id: "operating.continuation_write",
    intent: "write_continuation",
    title: "Write Continuation",
    operation_class: "mutation",
    handler_id: "write_continuation",
    input_schema: objectSchema({
      active_objective: { type: "string", maxLength: 500 },
      current_phase: { type: "string", maxLength: 120 },
      completed_evidence: { type: "array", maxItems: 20, items: { type: "string", maxLength: 200 } },
      next_action: { type: "string", maxLength: 300 },
    }, ["active_objective", "current_phase", "completed_evidence", "next_action"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "bounded_output"],
    tests: ["write_continuation persists bounded state", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.repository_inspection",
    intent: "inspect_repository",
    title: "Inspect Repository",
    operation_class: "read",
    handler_id: "inspect_repository",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_metadata_config"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["inspect_repository returns compact repo state"],
  }),
  capability({
    id: "engineering.repo_file_read",
    intent: "read_repo_file",
    title: "Read Repository File",
    operation_class: "read",
    handler_id: "read_repo_file",
    input_schema: objectSchema({
      path: { type: "string", enum: allowedRepoPaths },
      ref: { type: "string", maxLength: 80 },
      start_line: { type: "number", minimum: 1 },
      max_lines: { type: "number", minimum: 1, maximum: 120 },
    }, ["path"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_paths: allowedRepoPaths,
    external_systems: ["bundled_repo_snapshot"],
    risk_gates: ["auth_required", "session_required", "path_allowlist", "bounded_output"],
    tests: ["read_repo_file only reads allowed paths", "forbidden path traversal rejects"],
  }),
  capability({
    id: "engineering.repo_files_list",
    intent: "list_repo_files",
    title: "List Repository Files",
    operation_class: "read",
    handler_id: "list_repo_files",
    input_schema: objectSchema({
      path: { type: "string", maxLength: 220 },
      ref: { type: "string", maxLength: 80 },
    }, []),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_paths: allowedRepoPaths,
    external_systems: ["github_contents_api"],
    risk_gates: ["auth_required", "session_required", "path_allowlist", "bounded_output"],
    tests: ["list_repo_files returns only allowlisted paths"],
  }),
  capability({
    id: "engineering.repo_patch_set",
    intent: "apply_repo_patch_set",
    title: "Apply Repository Patch Set",
    operation_class: "mutation",
    handler_id: "apply_repo_patch_set",
    input_schema: objectSchema({
      dry_run: { type: "boolean" },
      commit_message: { type: "string", maxLength: 160 },
      expected_head_sha: { type: "string", maxLength: 40 },
      replacements: {
        type: "array",
        minItems: 1,
        maxItems: 20,
        items: objectSchema({
          path: { type: "string", maxLength: 220 },
          find: { type: "string", maxLength: 12000 },
          replace: { type: "string", maxLength: 12000 },
        }, ["path", "find", "replace"]),
      },
    }, ["replacements"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_paths: allowedRepoPaths,
    external_systems: ["github_git_data_api"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "path_allowlist", "exact_find_replace", "single_commit", "no_arbitrary_shell"],
    tests: ["apply_repo_patch_set dry-runs exact replacements", "apply_repo_patch_set rejects non-unique matches", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.repo_file_create",
    intent: "create_repo_file",
    title: "Create Repository File",
    operation_class: "mutation",
    handler_id: "create_repo_file",
    input_schema: objectSchema({
      path: { type: "string", maxLength: 220 },
      content: { type: "string", maxLength: 50000 },
      commit_message: { type: "string", maxLength: 160 },
      expected_head_sha: { type: "string", maxLength: 40 },
    }, ["path", "content"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_git_data_api"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "path_allowlist", "single_commit"],
    tests: ["create_repo_file creates only allowed paths", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.repo_file_delete",
    intent: "delete_repo_file",
    title: "Delete Repository File",
    operation_class: "mutation",
    handler_id: "delete_repo_file",
    input_schema: objectSchema({
      path: { type: "string", maxLength: 220 },
      commit_message: { type: "string", maxLength: 160 },
      expected_head_sha: { type: "string", maxLength: 40 },
    }, ["path"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_git_data_api"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "path_allowlist", "single_commit"],
    tests: ["delete_repo_file deletes only allowed paths", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.validation",
    intent: "run_validation",
    title: "Run Validation",
    operation_class: "mutation",
    handler_id: "run_validation",
    input_schema: objectSchema({
      validation: {
        type: "string",
        enum: ["npm test", "npm run check", "production market data commission", "production paper ledger commission", "production baseline bench commission", "production hostile judge commission", "production strategy factory commission", "production champion selection commission"],
      },
    }, ["validation"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: ["npm test", "npm run check"],
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "no_arbitrary_shell"],
    tests: ["run_validation returns explicit not_available_in_worker_runtime", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.github_actions_runs_list",
    intent: "list_github_actions_runs",
    title: "List GitHub Actions Runs",
    operation_class: "read",
    handler_id: "list_github_actions_runs",
    input_schema: objectSchema({
      workflow_id: { type: "string", enum: allowedWorkflowIds },
      limit: { type: "number", minimum: 1, maximum: 20 },
    }, []),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: allowedWorkflowIds,
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "github_token_server_side", "bounded_output"],
    tests: ["list_github_actions_runs returns compact run metadata", "missing GitHub token is reported without exposing secrets"],
  }),
  capability({
    id: "engineering.github_workflow_dispatch",
    intent: "trigger_github_workflow",
    title: "Trigger GitHub Workflow",
    operation_class: "mutation",
    handler_id: "trigger_github_workflow",
    input_schema: objectSchema({
      workflow_id: { type: "string", enum: allowedWorkflowIds },
      ref: { type: "string", maxLength: 80 },
      deploy_sha: { type: "string", maxLength: 40 },
    }, ["workflow_id"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: allowedWorkflowIds,
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "workflow_allowlist", "no_arbitrary_shell"],
    tests: ["trigger_github_workflow dispatches only allowlisted workflows", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "engineering.github_workflow_monitor",
    intent: "monitor_github_workflow",
    title: "Monitor GitHub Workflow",
    operation_class: "read",
    handler_id: "monitor_github_workflow",
    input_schema: objectSchema({
      run_id: { type: "string", maxLength: 30 },
    }, ["run_id"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["github_actions"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["monitor_github_workflow returns compact run and job state"],
  }),
  capability({
    id: "deployment.cloudflare_worker_dispatch",
    intent: "deploy_cloudflare_worker",
    title: "Deploy Cloudflare Worker",
    operation_class: "mutation",
    handler_id: "deploy_cloudflare_worker",
    input_schema: objectSchema({
      deploy_sha: { type: "string", maxLength: 40 },
    }, ["deploy_sha"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: ["quant-lab-deploy.yml"],
    external_systems: ["github_actions", "cloudflare"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "exact_sha_required", "cloudflare_secret_stays_in_github_actions"],
    tests: ["deploy_cloudflare_worker dispatches the fixed deploy workflow with an exact SHA", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "deployment.d1_migrations_dispatch",
    intent: "apply_d1_migrations",
    title: "Apply D1 Migrations",
    operation_class: "mutation",
    handler_id: "apply_d1_migrations",
    input_schema: objectSchema({
      deploy_sha: { type: "string", maxLength: 40 },
    }, ["deploy_sha"]),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    allowed_actions: ["quant-lab-deploy.yml"],
    external_systems: ["github_actions", "cloudflare_d1"],
    risk_gates: ["auth_required", "session_required", "idempotency_required", "exact_sha_required", "cloudflare_secret_stays_in_github_actions", "no_arbitrary_sql"],
    tests: ["apply_d1_migrations dispatches fixed workflow in migrations mode", "repeating same operation_id replays receipt"],
  }),
  capability({
    id: "deployment.production_alignment",
    intent: "validate_production_sha",
    title: "Validate Production SHA",
    operation_class: "read",
    handler_id: "validate_production_sha",
    input_schema: objectSchema({}),
    output_schema: objectSchema({ ok: { type: "boolean" } }, ["ok"]),
    external_systems: ["worker_env", "github_metadata_config"],
    risk_gates: ["auth_required", "session_required", "bounded_output"],
    tests: ["validate_production_sha returns compact alignment fields"],
  }),
];

export const lifecycleDeclarations = lifecycle.declarations;
export const lifecycleMandatorySequence = lifecycle.mandatory_sequence;

export function resolveCapability(intent) {
  return capabilityDirectory.find((entry) => entry.intent === intent) || null;
}

function capability(entry) {
  return {
    max_response_bytes: 12000,
    lifecycle_declaration_id: `${entry.id}.lifecycle`,
    ...entry,
  };
}
